// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xa98df793ff931f7an;
/**
* The available colors.
*
*/
export const Color = {
  /**
* Red color.
*
*/
  RED: 0,
  GREEN: 1,
  /**
* Blue color.
*
*/
  BLUE: 2
} as const;
export type Color = (typeof Color)[keyof typeof Color];
/**
* A named service.
*
*/
export const Service_Which = {
  /**
* Catches missing union member.
*
*/
  UNSPECIFIED: 0,
  /**
* A Worker.
*
*/
  WORKER: 1,
  NETWORK: 2
} as const;
export type Service_Which = (typeof Service_Which)[keyof typeof Service_Which];
/**
* A named service.
*
*/
export class Service extends $.Struct {
  static readonly UNSPECIFIED = Service_Which.UNSPECIFIED;
  static readonly WORKER = Service_Which.WORKER;
  static readonly NETWORK = Service_Which.NETWORK;
  static readonly _capnp = {
    displayName: "Service",
    id: "acf844b15d5d7d31",
    size: new $.ObjectSize(8, 1),
  };
  /**
* Service name.
*
*/
  get name(): string {
    return $.utils.getText(0, this);
  }
  set name(value: string) {
    $.utils.setText(0, value, this);
  }
  get _isUnspecified(): boolean {
    return $.utils.getUint16(0, this) === 0;
  }
  set unspecified(_: true) {
    $.utils.setUint16(0, 0, this);
  }
  get _isWorker(): boolean {
    return $.utils.getUint16(0, this) === 1;
  }
  set worker(_: true) {
    $.utils.setUint16(0, 1, this);
  }
  get _isNetwork(): boolean {
    return $.utils.getUint16(0, this) === 2;
  }
  set network(_: true) {
    $.utils.setUint16(0, 2, this);
  }
  toString(): string { return "Service_" + super.toString(); }
  which(): Service_Which {
    return $.utils.getUint16(0, this) as Service_Which;
  }
}
